// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmmlcayednczwbojdhqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtbWxjYXllZG5jendib2pkaHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NzE1MzMsImV4cCI6MjA1NzU0NzUzM30.S3Rl1oKBb1zzbcBFd-zOu8d_gMBCCssBFlRiTPP5oDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);